"use client";

import network from "@/utils/network";
import "./globals.css";
import { ThirdwebProvider } from "@thirdweb-dev/react";

export const metadata = {
	title: "Ebay Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ThirdwebProvider activeChain={network}>
				<body>{children}</body>
			</ThirdwebProvider>
		</html>
	);
}
